### ISSUE TITLE
training a new point cloud -> ShapeAssembly model

### ISSUE THREAD

**Issue by Mdemerdash** [rkjones4/ShapeAssembly#10]
Hi, 
Firstly. thank you for your previous support on the earlier issue. 

I need assistance in training a new point cloud encoder and decoder. Please correct me If I misunderstood the procedure to train a new point cloud ShapeAssembly model:

1- Create 3d CAD model for each point cloud in my dataset.
2-  Annotate these shapes in the online browser provided by PartNet.
3- Sample the surface of these annotated CAD models with point clouds using sample_partnet.py -> is there a special command for this one?
4- Output the .json files that include the hierarchical graphs for these point clouds
5- Execute the command python3 gen_data.py {category}
6- Feed train_pc_encoder.py with the generated programs from step 5 -> could you kindly provide a command example for that? 

Kind regards,
Mohamed

**Comment by rkjones4** [comment]
There are two general approaches you can take for learning a PC -> ShapeAssembly model.

Approach 1 requires GT ShapeAssembly programs for the PC dataset you are interested in. This requires finding GT SA programs for your domain of interest (for a training set of shapes, probably around ~1k shapes atleast). Steps 1-5 that you listed would accomplish this. From there you could either: directly train a PC -> Program model, or you could train a Program->Program VAE, and learn a mapping from a PC into this latent space. This latter approach is what we did in ShapeAssembly for PartNet data. 

The other approach (Approach 2) would be to try to learn a PC->program model without supervised programs for your training set. This is a harder problem, but the advantage is that you don't have to figure out how to heuristically convert shapes into programs (this can be learned). https://github.com/rkjones4/PLAD might be a good starting point if you take this approach.
