### ISSUE TITLE
 How to train a model from point clouds to ShapeAssembly？

### ISSUE THREAD

**Issue by licy02** [rkjones4/ShapeAssembly#11]
If I want to train a model from point clouds to ShapeAssembly on my own, what should I train first, what should I train later, and I didn't find the code for training the decoder in pc_data?

**Comment by rkjones4** [comment]
Hi @licy02, thanks for your interest!

Have you seen the discussions in these two issues, they may be of interest to you:

https://github.com/rkjones4/ShapeAssembly/issues/10

https://github.com/rkjones4/ShapeAssembly/issues/4

In short, the steps we took were:
- first train a program to program VAE (e.g. our main generative network)
- freeze the above model, and using paired (point cloud, program) training data, train a point cloud encoder to map point clouds into the latent space of the program-program VAE.

Please let me know if that helps!

**Comment by licy02** [comment]
Thank you, this is very helpful for me. I appreciate your excellent work and detailed responses.

**Comment by rkjones4** [comment]
Great to hear that is was helpful, in that case I'll close this issue for now, but please feel free to re-open if something else comes up!
