### ISSUE TITLE
Test on arbitrary point cloud data

### ISSUE THREAD

**Issue by Enigma-li** [rkjones4/ShapeAssembly#2]
Hi,

Excellent work!

I am curious to know the performance of the testing on arbitrary shape by feeding the point cloud as input. Is there the script to support this kind of test?

**Comment by rkjones4** [comment]
Hi - thanks for your comments!

We are currently planning on releasing the pre-trained model for the chairs category. This model learns to map point clouds sampled on the surfaces of chairs from the dense geometry in PartNet to ShapeAssembly programs. Hopefully, this code will be added in the next few days.

Would this model support your use case?

If there is interest, we may also generalize the training pipeline to take in other sources of point cloud data / other PartNet categories. There are some data-processing steps involved in getting this to work end-to-end, so it may take a bit of time to release. In the mean-time, I am also happy to answer any questions you might have about the details of the method, if any description in the paper is unclear.

Best,
Kenny

**Comment by Enigma-li** [comment]
Thanks for your kind reply! I will wait for your released pre-trained model for chairs category.

I recall that you trained your model per-category, but I want to test a general point could fitting. Is it possible to train all categories together?

**Comment by rkjones4** [comment]
Hi Changjian, 

I've just released our pre-trained point-cloud -> ShapeAssembly models, please see the README for how to set them up and let me know if you have any questions.

Additionally, I added the files used to train these models to the pc_data directory. With some slight modifications, you should be able to train a new point cloud -> ShapeAssembly model on a different set of point clouds (as long as you have paired ShapeAssembly program data). Please let me know if anything in the paper describing our training procedure is unclear.

Best,
Kenny
