### ISSUE TITLE
About code/pointnet2/utils/pytorch_utils

### ISSUE THREAD

**Issue by jiayaozhang** [rkjones4/ShapeAssembly#5]
Hi, when I follow the Readme.md in Pointnet2 module, I found that we have to use the 

https://github.com/erikwijmans/Pointnet2_PyTorch/tree/pytorch-0.4.0

But when I open the untils in shows that the

in erikwijmans/Pointnet2_PyTorch/utils/pytorch_utils  is not found

So I am wondering could you provide the Pytorch_utils?

Thanks a lot!

**Comment by rkjones4** [comment]
Yes it looks like this file was removed in commit https://github.com/erikwijmans/Pointnet2_PyTorch/commit/22e8cf527b696b63b66f3873d80ae5f93744bdef --> you would either need to clone from the repo before that commit, or use a different PointNet implementation

**Comment by jiayaozhang** [comment]
Yes, I clone from the repo before that commit and now it has been fixed, thanks.
