### ISSUE TITLE
python3 example_fit.py data/table/18157.txt data/examples/comp_pc.obj fit

### ISSUE THREAD

**Issue by keun-jang** [rkjones4/ShapeAssembly#7]
I am running "**example_fit.py**" on colab:
### !python3 example_fit.py data/table/18157.txt data/examples/comp_pc.obj fit

and getting **error** like this:
Traceback (most recent call last):
  File "example_fit.py", line 77, in <module>
    main()
  File "example_fit.py", line 66, in main
    **loss.backward()**
  File "/usr/local/lib/python3.7/dist-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/__init__.py", line 149, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
### RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor []], which is output 0 of SelectBackward, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

Kindly, take a look on it...

**Comment by rkjones4** [comment]
Hm, I've just tried running that same command within my virtual envrionment and it works as expected. Please find the parameters of the conda env I am using in the linked file: [reqs.txt](https://github.com/rkjones4/ShapeAssembly/files/7822862/reqs.txt). 

It may be the case that colab is running a different version of PyTorch, which causes this issue.
