### ISSUE TITLE
AttributeError: 'GRU' object has no attribute '_flat_weights_names'

### ISSUE THREAD

**Issue by Mdemerdash** [rkjones4/ShapeAssembly#9]
Hi, this paper has my full attention :) Could you please help me? I'm trying to run the pre trained model for pc that is in the data under:
https://drive.google.com/file/d/1jmSWAKOr_pBVfmZb6g0bjkySaGxPTxTF/view?usp=sharing

however when I run : 
python3 chair_program_from_pc.py test_pc 2307

I get the error : 
AttributeError: 'GRU' object has no attribute '_flat_weights_names'

Any help?

**Comment by rkjones4** [comment]
Hi! 

Thank you for your interest :) 

This looks like a versioning issue with PyTorch, which version are you trying to use? This model was saved with PyTorch 1.3.0

**Comment by Mdemerdash** [comment]
Hi, 
thank you so much for taking the time. 

I'm following the guide line , so I'm activating the pgb env then installing Pointnet2/Pointnet++ PyTorch and end up with torch version = 1.11.0.

I also have CUDA 11.1 when querying CUDA version through nvcc --version.

Do I need to uninstall CUDA 11.1 and install 10.2 with a 1.3 torch? 



I tried installing torch 1.3"pip install torch==1.3.0" and i did successfully but then I got the following error while installing torch 1.3:
ERROR: pointnet2-ops 3.0.0 has requirement torch>-1.4, but you'll have torch 1.3.0 which is incompatible.


Still tried my luck with torch 1.3 installed and ran : /ShapeAssembly/code# python3 chair program from pc.py test pc 2307

but I got:

pybullet build time: Apr 14 2020 20:57:34
Traceback (most recent call last):
File
"chair program from pe.py"
, line 80, in
‹modules
eval recon (sys.argu[l],sys.argv[2:])
chvisio
File "chair program from pc.py"
line 29, in eval recon
encoder. load state
dict (torch. load (point cloud encoder) )
ver
File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py",line 839, in load state dict
self-class-name "In\t". join (error msgs) ))13
RuntimeError:
Error (s) in loading state dict for PCEncoder:
Missing key (s) in state dict:
"A modules.0.mlps.0.0.weight",
"SA modules. 0.mlps.0.1.weight",
etc etc

**Comment by rkjones4** [comment]
All of the requirements should be listed inside of [code/env.yml](https://github.com/rkjones4/ShapeAssembly/blob/master/code/env.yml)

This code has been tested with cuda 10.0 and PyTorch 1.3 , with other versions of either it may or may not work.

For this specific issue, you could try just downloading cuda 10.2, loading the model from the .pt, and then saving only the state dict of the model -- looking through google searches this might have a better chance of not running into backwards compatibility issue with PyTorch LSTM/GRU classes; that said, I don't know whether the rest of the pipeline would work with different torch/cuda versions.

Hope that helps!

**Comment by rkjones4** [comment]
Please see this issue: https://github.com/rkjones4/ShapeAssembly/issues/5, I think you would need to install a previous version of the PointNet utils repo

**Comment by Mdemerdash** [comment]
Hi Russle, after some suffering it worked with an older commit. Thank you so much.
